### ISSUE TITLE
Need Prograud Config?

### ISSUE THREAD

**Issue by dineshmm23** [leandroBorgesFerreira/LoadingButtonAndroid#122]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method b.a.b.g.b, parameter bitmap
        at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.a(Unknown Source:2)
        at com.entriver.giffy.fragment.OtpVerificationFragment$2.a(Unknown Source:262)
        at e.h$a$1$1.run(Unknown Source:41)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by leandroBorgesFerreira** [comment]
Hello, could you provide more context and detail? It is hard to understand the problem just with the stack trace.

**Comment by dineshmm23** [comment]
Sorry , not provide details.

> This happens only in release mode :->
  ```
Bitmap bitmap = BitmapFactory.decodeResource(mContext.getResources(), R.drawable.ic_check_white_24dp);
btnUpdateStatus.doneLoadingAnimation(R.color.green_complete, bitmap);
```
When using the above method without any progaurd rule...it carshes the app.. 

So currently I don't know what progaurd rules to add to it...so if possible any `Proguard rules` if add may fix the issues I think...

**Comment by leandroBorgesFerreira** [comment]
Proguard normally only remove code that doesn't have direct access... like reflection stuff. That's odd... I'll take a look

**Comment by HeyIts-RJ** [comment]
This issue is still there and app is crashing.
