### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by MohammadRezaei92** [leandroBorgesFerreira/LoadingButtonAndroid#171]
br.com.simplepass.loadingbutton.animatedDrawables.CircularRevealAnimatedDrawable$readyImage$2.invoke (CircularRevealAnimatedDrawable.java:38)
br.com.simplepass.loadingbutton.animatedDrawables.CircularRevealAnimatedDrawable$readyImage$2.invoke (CircularRevealAnimatedDrawable.java:23)
kotlin.SynchronizedLazyImpl.getValue (SynchronizedLazyImpl.java:74)
br.com.simplepass.loadingbutton.animatedDrawables.CircularRevealAnimatedDrawable.getReadyImage (CircularRevealAnimatedDrawable.java:6)
br.com.simplepass.loadingbutton.animatedDrawables.CircularRevealAnimatedDrawable.draw (CircularRevealAnimatedDrawable.java:106)
br.com.simplepass.loadingbutton.customViews.CircularProgressButton.drawDoneAnimation (CircularProgressButton.java:121)
br.com.simplepass.loadingbutton.presentation.ProgressButtonPresenter.onDraw (ProgressButtonPresenter.java:67)
br.com.simplepass.loadingbutton.customViews.CircularProgressButton.onDraw (CircularProgressButton.java:179)

**Comment by leandroBorgesFerreira** [comment]
Hello hello. Could you explain more what is the problem?

**Comment by MohammadRezaei92** [comment]
> Hello hello. Could you explain more what is the problem?

My app crash when user click on the button and this is a stack-trace

```
java.lang.IllegalArgumentException: width and height must be > 0
at android.graphics.Bitmap.createBitmap(Bitmap.java:1148)
at android.graphics.Bitmap.createBitmap(Bitmap.java:987)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:842)
at z.a.a.a.a.g$g.invoke(SourceFile:1)
at f0.j.getValue(SourceFile:5)
at z.a.a.a.a.g.draw(SourceFile:6)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.o(SourceFile:1)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.o(SourceFile:1)
at z.a.a.a.c.b.a(SourceFile:5)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.onDraw(SourceFile:2)
at br.com.simplepass.loadingbutton.customViews.CircularProgressButton.onDraw(SourceFile:2)

```
