### ISSUE TITLE
java.lang.NullPointerException on emulator running 19 api

### ISSUE THREAD

**Issue by MadAxon** [leandroBorgesFerreira/LoadingButtonAndroid#51]
The library works on android 5.1 and above(both emulators and real phones) and there is no problem. However, when I ran my app on the emulator(19 level API), the app got crashed.
I don't know whether there is the same problem on the real phone running 19 API. 

Stacktrace:
`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.app.test, PID: 4578
                                                                java.lang.NullPointerException
                                                                    at android.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:505)
                                                                    at android.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:487)
                                                                    at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:517)
                                                                    at android.animation.ValueAnimator.start(ValueAnimator.java:936)
                                                                    at android.animation.ValueAnimator.start(ValueAnimator.java:946)
                                                                    at android.animation.ObjectAnimator.start(ObjectAnimator.java:465)
                                                                    at android.animation.AnimatorSet.start(AnimatorSet.java:563)
                                                                    at br.com.simplepass.loading_button_lib.customViews.CircularProgressButton.d(CircularProgressButton.java:513)
                                                                    at com.app.test.MainActivity.m(MainActivity.java:123)
                                                                    at com.app.test.MainActivity.onClick(MainActivity.java:54)
                                                                    at android.view.View.performClick(View.java:4438)
                                                                    at android.view.View$PerformClick.run(View.java:18422)
                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                    at dalvik.system.NativeStart.main(Native Method)`

The app crashes at line `circularProgressButton.startAnimation();`

Is the library compatible with emulators? And does it work with prelollipop devices?

**Comment by leandroBorgesFerreira** [comment]
The library works normally in emulators with API 19. You can test the sample of this repository in an emulator with API 19 to see that it works normally. Could you provide the code that made this bug, so I can help you?

**Comment by sinadalvand** [comment]
I have same issue ! how i can solve this ?!

**Comment by leandroBorgesFerreira** [comment]
@sinadalvand Could you provide the code that made your crash? Or more detail about your problem?

**Comment by sinadalvand** [comment]
After many error tests i understand this error happen while call margin top in XML in this button tag ;

why? and just crash in android 4.4

**Comment by MrStahlfelge** [comment]
Tested it on a real device, it works for me.

**Comment by leandroBorgesFerreira** [comment]
It works in those versions without problems. Maybe what caused those NPE what some specific usage, but I can't help without some code/details about the problem.

**Comment by votruk** [comment]
I have the same issue. Not only on emulator but on Samsung Galaxy s3 too

**Comment by votruk** [comment]
In my case crash happened when I have no target in ObjectAnimator that animates corners because mGradientDrawable for that moment equals to null. Solved by assigning some drawable in xml as a background.

**Comment by leandroBorgesFerreira** [comment]
This library was reimplemented. Try to use the version 2.0.6 instead of 1.14.0.
